### ISSUE TITLE
'table.new' and 'table.clear' not found when required

### ISSUE THREAD

**Issue by lidh15** [openresty/lua-tablepool#10]
no field package.preload['table.new'] and no field package.preload['table.clear']
what should I install to handle with it?

**Comment by dndx** [comment]
Please use LuaJIT, PuC Lua does not support these.

**Comment by lidh15** [comment]
okay, I saw this is a extension in LuaJIT 2.1, so does that means I cannot use tablepool without LuaJIT 2.1+?

**Comment by dndx** [comment]
No you can't. We do not develop or test these libraries on non-LuaJIT.
